### ISSUE TITLE
cant map button and excess processes running? 

### ISSUE THREAD

**Issue by bozzy01** [CoolerMasterTechnology/Pi-Tool#10]
Button mapping is not working... I get an error that says "Please add at least one button press!".. It will not allow me to click either of the button press types to add.. Further more the tool keeps adding a bunch of processes that I see as pi tool in task manager is that normal?

**Comment by mntns** [comment]
Just to make sure: Have you tried dragging the button press types instead of clicking them? It could be a future addition that this behaviour is made clearer or that clicking is also allowed. 

Regarding the processes: The GUI definitely uses a bit of resources (as Electron basically runs a fully blown browser), but as soon as it is minimized, the resource usage should be very small.
